{"uid":"ae221c6951c32ab1","name":"test_auth_user_with_random_data","fullName":"tests.authorization.test_auth.TestAuthUser#test_auth_user_with_random_data","historyId":"ec1452550068c8ac52f2451b59bb37d1","time":{"start":1755005678529,"stop":1755005678535,"duration":6},"description":"\n        1. Try to auth user (access to store) with random invalid data\n        2. Check that status code is 401\n        3. Check response\n        ","descriptionHtml":"<pre><code>    1. Try to auth user (access to store) with random invalid data\n    2. Check that status code is 401\n    3. Check response\n</code></pre>\n","status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":true,"beforeStages":[{"name":"_session_faker","time":{"start":1755005678507,"stop":1755005678508,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"app","time":{"start":1755005678508,"stop":1755005678508,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"attachmentStep":false,"stepsCount":0,"hasContent":false}],"testStage":{"description":"\n        1. Try to auth user (access to store) with random invalid data\n        2. Check that status code is 401\n        3. Check response\n        ","status":"passed","steps":[],"attachments":[{"uid":"3050e24b39910196","name":"log","source":"3050e24b39910196.txt","type":"text/plain","size":419}],"parameters":[],"attachmentsCount":1,"shouldDisplayMessage":false,"attachmentStep":false,"stepsCount":0,"hasContent":true},"afterStages":[],"labels":[{"name":"tag","value":"negative"},{"name":"parentSuite","value":"tests.authorization"},{"name":"suite","value":"test_auth"},{"name":"subSuite","value":"TestAuthUser"},{"name":"host","value":"ixx"},{"name":"thread","value":"27672-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.authorization.test_auth"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"48d31eb51097c582","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /auth (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001FDACA50AD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))","time":{"start":1755005539151,"stop":1755005541191,"duration":2040}}],"categories":[],"tags":["negative"]},"source":"ae221c6951c32ab1.json","parameterValues":[]}