{"name": "test_auth_user_with_random_data", "status": "passed", "description": "\n        1. Try to auth user (access to store) with random invalid data\n        2. Check that status code is 401\n        3. Check response\n        ", "attachments": [{"name": "log", "source": "21844f2e-ef6d-4afc-a239-d320c6b65e45-attachment.txt", "type": "text/plain"}], "start": 1755009319761, "stop": 1755009319769, "uuid": "0dc729bc-4bda-45ed-86c9-3ac351f7ea40", "historyId": "ec1452550068c8ac52f2451b59bb37d1", "testCaseId": "ec1452550068c8ac52f2451b59bb37d1", "fullName": "tests.authorization.test_auth.TestAuthUser#test_auth_user_with_random_data", "labels": [{"name": "tag", "value": "negative"}, {"name": "parentSuite", "value": "tests.authorization"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestAuthUser"}, {"name": "host", "value": "ixx"}, {"name": "thread", "value": "1912-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.authorization.test_auth"}], "titlePath": ["tests", "authorization", "test_auth.py", "TestAuthUser"]}