{"name": "test_auth_user_with_random_data", "status": "passed", "description": "\n        1. Try to auth user (access to store) with random invalid data\n        2. Check that status code is 401\n        3. Check response\n        ", "attachments": [{"name": "log", "source": "32863f7b-0277-4e75-a0bf-3317c27e8000-attachment.txt", "type": "text/plain"}], "start": 1755006584330, "stop": 1755006584333, "uuid": "ff4d6058-9460-4278-b609-ff21afee2319", "historyId": "ec1452550068c8ac52f2451b59bb37d1", "testCaseId": "ec1452550068c8ac52f2451b59bb37d1", "fullName": "tests.authorization.test_auth.TestAuthUser#test_auth_user_with_random_data", "labels": [{"name": "tag", "value": "negative"}, {"name": "parentSuite", "value": "tests.authorization"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestAuthUser"}, {"name": "host", "value": "ixx"}, {"name": "thread", "value": "20916-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.authorization.test_auth"}], "titlePath": ["tests", "authorization", "test_auth.py", "TestAuthUser"]}