{"name": "test_auth_user_with_random_data", "status": "passed", "description": "\n        1. Try to auth user (access to store) with random invalid data\n        2. Check that status code is 401\n        3. Check response\n        ", "attachments": [{"name": "log", "source": "a890c3c3-b22e-473f-9bec-34ac3ae429a3-attachment.txt", "type": "text/plain"}], "start": 1755009028985, "stop": 1755009028990, "uuid": "865ea8dc-e25f-4da5-9dd4-05c33361bcdf", "historyId": "ec1452550068c8ac52f2451b59bb37d1", "testCaseId": "ec1452550068c8ac52f2451b59bb37d1", "fullName": "tests.authorization.test_auth.TestAuthUser#test_auth_user_with_random_data", "labels": [{"name": "tag", "value": "negative"}, {"name": "parentSuite", "value": "tests.authorization"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestAuthUser"}, {"name": "host", "value": "ixx"}, {"name": "thread", "value": "21132-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.authorization.test_auth"}], "titlePath": ["tests", "authorization", "test_auth.py", "TestAuthUser"]}