{"name": "test_auth_user_with_random_data", "status": "passed", "description": "\n        1. Try to auth user (access to store) with random invalid data\n        2. Check that status code is 401\n        3. Check response\n        ", "attachments": [{"name": "log", "source": "12727d30-ac15-4d49-b124-a75d3113759a-attachment.txt", "type": "text/plain"}], "start": 1755008989836, "stop": 1755008989841, "uuid": "0d5a608d-7625-4266-aa4d-392cd119472e", "historyId": "ec1452550068c8ac52f2451b59bb37d1", "testCaseId": "ec1452550068c8ac52f2451b59bb37d1", "fullName": "tests.authorization.test_auth.TestAuthUser#test_auth_user_with_random_data", "labels": [{"name": "tag", "value": "negative"}, {"name": "parentSuite", "value": "tests.authorization"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestAuthUser"}, {"name": "host", "value": "ixx"}, {"name": "thread", "value": "34744-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.authorization.test_auth"}], "titlePath": ["tests", "authorization", "test_auth.py", "TestAuthUser"]}