{"name": "test_auth_user_with_random_data", "status": "passed", "description": "\n        1. Try to auth user (access to store) with random invalid data\n        2. Check that status code is 401\n        3. Check response\n        ", "attachments": [{"name": "log", "source": "94b59b97-4814-4f0a-8706-b94a6a36cf96-attachment.txt", "type": "text/plain"}], "start": 1755003365363, "stop": 1755003365369, "uuid": "6b28865a-a7cb-4f02-bf09-a2045ebcc37f", "historyId": "ec1452550068c8ac52f2451b59bb37d1", "testCaseId": "ec1452550068c8ac52f2451b59bb37d1", "fullName": "tests.authorization.test_auth.TestAuthUser#test_auth_user_with_random_data", "labels": [{"name": "tag", "value": "negative"}, {"name": "parentSuite", "value": "tests.authorization"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestAuthUser"}, {"name": "host", "value": "ixx"}, {"name": "thread", "value": "21144-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.authorization.test_auth"}], "titlePath": ["tests", "authorization", "test_auth.py", "TestAuthUser"]}